name: Vespa-CI
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
#  push:
#    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  code-checks_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: latest

      - name: Installing dependencies
        run: npm ci

      - name: Stylelint
        run: npm run lint-stylelint

      - name: Eslint
        run: npm run lint-eslint

      - name: Type check
        run: npm run type-check

      - name: Unit test
        run: npm run test:unit

      - name: Build project
        run: npm run build